package com.jilali.crypto;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;
import java.security.SecureRandom;

/**
 * QQTEA — Tencent QQ's TEA variant, CBC-like chaining, used by HelloTalk's {@code ht_im/sock}
 * binary protocol to encrypt push-notification payloads once a session key is negotiated.
 * Ported field-for-field from the reference client ({@code connectwebsock.js}'s {@code QQTEA}
 * object) — same block transform, same chaining, same random-padded header/trailer scheme.
 * Verified against test vectors generated by running the original JS directly (see commit
 * notes): same key, same plaintext, byte-identical ciphertext.
 *
 * <p>Decrypted output always carries the documented trailing zero-padding bytes (7, from the
 * encrypt side's {@code trailingLen}) — callers strip them the same way the reference client
 * does ({@code .replace(/\0/g, '')} on the decoded string), not this class's job.
 */
public final class QqTeaCipher {

    private static final int DELTA = 0x61C88647;
    private static final SecureRandom RANDOM = new SecureRandom();

    private QqTeaCipher() {}

    public static byte[] decrypt(byte[] buffer, byte[] key) {
        if (buffer == null || buffer.length < 8) return null;
        return decryptCore(buffer, key);
    }

    /** @param key 16 bytes. */
    public static byte[] encrypt(byte[] buffer, byte[] key) {
        if (buffer == null) return null;
        int headerLen = (8 - (buffer.length + 10) % 8) % 8 + 3;
        int trailingLen = 7;
        int totalLen = buffer.length + headerLen + trailingLen;
        byte[] padded = new byte[totalLen];
        padded[0] = (byte) ((headerLen - 3) & 0x07);
        for (int i = 1; i < headerLen; i++) {
            padded[i] = (byte) RANDOM.nextInt(256);
        }
        System.arraycopy(buffer, 0, padded, headerLen, buffer.length);
        return encryptCore(padded, key);
    }

    private static int[] readKeyWords(byte[] key) {
        ByteBuffer kb = ByteBuffer.wrap(key).order(ByteOrder.LITTLE_ENDIAN);
        return new int[] { kb.getInt(0), kb.getInt(4), kb.getInt(8), kb.getInt(12) };
    }

    private static int[] decryptBlock(int v0, int v1, int[] k) {
        int sum = 0xE3779B90;
        for (int i = 0; i < 16; i++) {
            int term1 = ((v0 << 4) + k[2]) ^ (v0 + sum) ^ ((v0 >>> 5) + k[3]);
            v1 = v1 - term1;

            int term2 = ((v1 << 4) + k[0]) ^ (v1 + sum) ^ ((v1 >>> 5) + k[1]);
            v0 = v0 - term2;

            sum = sum + DELTA;
        }
        return new int[] { v0, v1 };
    }

    private static int[] encryptBlock(int v0, int v1, int[] k) {
        int sum = 0x9E3779B9;
        for (int i = 0; i < 16; i++) {
            int term2 = ((v1 << 4) + k[0]) ^ (v1 + sum) ^ ((v1 >>> 5) + k[1]);
            v0 = v0 + term2;

            int term1 = ((v0 << 4) + k[2]) ^ (v0 + sum) ^ ((v0 >>> 5) + k[3]);
            v1 = v1 + term1;

            sum = sum - DELTA;
        }
        return new int[] { v0, v1 };
    }

    private static byte[] decryptCore(byte[] buffer, byte[] key) {
        int[] k = readKeyWords(key);
        ByteBuffer in = ByteBuffer.wrap(buffer).order(ByteOrder.LITTLE_ENDIAN);
        int len = buffer.length;
        byte[] out = new byte[len];
        ByteBuffer outBuf = ByteBuffer.wrap(out).order(ByteOrder.LITTLE_ENDIAN);

        if (len < 8) return out;

        int c0 = in.getInt(0);
        int c1 = in.getInt(4);
        int[] d = decryptBlock(c0, c1, k);
        outBuf.putInt(0, d[0]);
        outBuf.putInt(4, d[1]);

        int prevD0 = d[0], prevD1 = d[1], prevC0 = c0, prevC1 = c1;

        for (int offset = 8; offset < len; offset += 8) {
            int curC0 = in.getInt(offset);
            int curC1 = in.getInt(offset + 4);
            int in0 = curC0 ^ prevD0;
            int in1 = curC1 ^ prevD1;
            int[] dec = decryptBlock(in0, in1, k);
            outBuf.putInt(offset, dec[0] ^ prevC0);
            outBuf.putInt(offset + 4, dec[1] ^ prevC1);
            prevD0 = dec[0];
            prevD1 = dec[1];
            prevC0 = curC0;
            prevC1 = curC1;
        }

        int padLen = (out[0] & 0x07) + 3;
        if (padLen < len) {
            byte[] stripped = new byte[len - padLen];
            System.arraycopy(out, padLen, stripped, 0, stripped.length);
            return stripped;
        }
        return out;
    }

    private static byte[] encryptCore(byte[] buffer, byte[] key) {
        int[] k = readKeyWords(key);
        ByteBuffer in = ByteBuffer.wrap(buffer).order(ByteOrder.LITTLE_ENDIAN);
        int len = buffer.length;
        byte[] out = new byte[len];
        ByteBuffer outBuf = ByteBuffer.wrap(out).order(ByteOrder.LITTLE_ENDIAN);

        int p0 = in.getInt(0);
        int p1 = in.getInt(4);
        int[] c = encryptBlock(p0, p1, k);
        outBuf.putInt(0, c[0]);
        outBuf.putInt(4, c[1]);

        int prevD0 = p0, prevD1 = p1, prevC0 = c[0], prevC1 = c[1];

        for (int offset = 8; offset < len; offset += 8) {
            int curP0 = in.getInt(offset);
            int curP1 = in.getInt(offset + 4);
            int dec0 = curP0 ^ prevC0;
            int dec1 = curP1 ^ prevC1;
            int[] enc = encryptBlock(dec0, dec1, k);
            int curC0 = enc[0] ^ prevD0;
            int curC1 = enc[1] ^ prevD1;
            outBuf.putInt(offset, curC0);
            outBuf.putInt(offset + 4, curC1);
            prevD0 = dec0;
            prevD1 = dec1;
            prevC0 = curC0;
            prevC1 = curC1;
        }

        return out;
    }
}
